### ISSUE TITLE
Add promise interface

### ISSUE THREAD

**Issue by angrykoala** [angrykoala/yerbamate#2]
Add a promise alternative to `run` callback.

The promise should reject when the returned code `isErrorCode` and reslve otherwise. In both cases, the promise will return both, the stdout and the stderr

**Comment by vincealdrin** [comment]
I will try to work on this today

**Comment by angrykoala** [comment]
This requires testing in #1

**Comment by angrykoala** [comment]
After some testing, the promise interface doesn't look to fit properly into the testing framework, as it provides a confusing interface for the purpose of yerbamate. For now the promise interface will be removed
